### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by deb75** [taiwins/taiwins#151] opened 2021-04-07 21:58 UTC
When issuing `meson build` in taiwins source directory, the only error I get is : 
```
Run-time dependency lua found: NO (tried pkgconfig and cmake)
```

I cannot figure out what is missing. After compiling and installing, I can launch `taiwins` without any particular error.

**Comment by xeechou** [comment] 2021-04-08 01:24
which version of Lua you have? it requires lua 5.3 and above

**Comment by deb75** [comment] 2021-04-09 15:29
`lua -v` gives : 
```
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
```

But there are other lua libraries installed, `aptitude search lua | grep ^i` : 
```
i A liblua5.1-0 - Shared library for the Lua interpreter version 5.1
i A liblua5.1-0-dev - Development files for the Lua language version 5.1
i A liblua5.2-0 - Shared library for the Lua interpreter version 5.2
i A liblua5.3-0 - Shared library for the Lua interpreter version 5.3
i  liblua5.3-dev - Development files for the Lua language version 5.3
i A libluajit-5.1-2 - Just in time compiler for Lua - library version
i A libluajit-5.1-common - Just in time compiler for Lua - common files
i  libluajit-5.1-dev - Just in time compiler for Lua - development files
i  lua5.3 - Simple, extensible, embeddable programming language
i  luajit - Just in time compiler for Lua programming language version 5.1
```

**Comment by deb75** [comment] 2021-04-09 15:37
I just reflect on my previous message.

The error first appears there : 
```
|Run-time dependency lua found: NO (tried pkgconfig and cmake)
|Run-time dependency lua-5.3 found: YES 5.3.3
```
Then later, the error is reported again : 
```
Run-time dependency lua found: NO (tried pkgconfig and cmake)
```

So, probably is it a harmless error ?

**Comment by xeechou** [comment] 2021-04-10 00:11
Taiwins is built with multiple subprojects, `twclient` and `nklua` submodules require lua runtime as well. Could you verify the error reported for which module? Thanks

**Comment by deb75** [comment] 2021-04-10 13:31
Here is where the error first appear : 
```
|Executing subproject nklua method meson 
|
|Project name: love-nuklear
|Project version: 0.1
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
|C linker for the host machine: cc ld.bfd 2.35.2
|Compiler for C supports arguments -Wno-unused-parameter: YES (cached)
|Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
|Compiler for C supports arguments -Wno-pedantic: YES (cached)
|Found CMake: /usr/bin/cmake (3.18.4)
|Run-time dependency lua found: NO (tried pkgconfig and cmake)
|Run-time dependency lua-5.3 found: YES 5.3.3
|Build targets in project: 17
|Subproject nklua finished.
```
in subproject `nklua`

**Comment by xeechou** [comment] 2021-04-12 01:24
Okay, it is no harm. The meson script was checking if either `lua >=5.3` or `lua-5.3` available. On some platform, ubuntu for instance. Official lua version is 5.1.

please see [here](https://github.com/xeechou/love-nuklear/blob/nklua/meson.build#L23) for details. 

I am closing this issue as it is not a bug.

**Closed by xeechou** 2021-04-12 01:24 UTC
